---
- hosts: all
  become: yes
  tasks:
    - name: Update apt repository and install dependencies
      apt:
        update_cache: yes
        name:
          - curl
          - tar
        state: present

    - name: Create actions-runner directory
      file:
        path: /home/ubuntu/actions-runner
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Download GitHub Actions runner package
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz
        dest: /home/ubuntu/actions-runner/actions-runner-linux-x64-2.319.1.tar.gz

    - name: Validate the hash (optional but recommended)
      shell: echo "3f6efb7488a183e291fc2c62876e14c9ee732864173734facc85a1bfb1744464  actions-runner-linux-x64-2.319.1.tar.gz" | shasum -a 256 -c
      args:
        chdir: /home/ubuntu/actions-runner/
      ignore_errors: yes

    - name: Extract GitHub Actions runner package
      unarchive:
        src: /home/ubuntu/actions-runner/actions-runner-linux-x64-2.319.1.tar.gz
        dest: /home/ubuntu/actions-runner/
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Configure GitHub Actions runner
      shell: ./config.sh --url https://github.com/manabpokhrel7/Ansible-CICD --token APWOE62C6EXC76B4K22PBPDGY5WFI
      args:
        chdir: /home/ubuntu/actions-runner/
        executable: /bin/bash
      become: yes

    - name: Start GitHub Actions runner service
      shell: |
        sudo ./svc.sh install
        sudo ./svc.sh start
      args:
        chdir: /home/ubuntu/actions-runner/
        executable: /bin/bash
      become: yes
